#!/bin/sh

SHOULDTEST = false

#Check tests repo for changes
cd ~/testing
git fetch origin
if [ `git log --pretty=%H ...refs/heads/master^` = `git ls-remote origin -h refs/heads/master |cut -f1` ]; then
	echo "Tests is up to date"
else
    echo "Pulling tests..."
    git pull
    SHOULDTEST = true
fi

#Check api repo for changes
cd ~/testing/api
git fetch origin
if [ `git log --pretty=%H ...refs/heads/master^` = `git ls-remote origin -h refs/heads/master |cut -f1` ]; then
	echo "Api is up to date"
else
    echo "Pulling tests..."
    git pull
    SHOULDTEST = true
fi

#Check api repo for changes
cd ~/testing/deployment
git fetch origin
if [ `git log --pretty=%H ...refs/heads/master^` = `git ls-remote origin -h refs/heads/master |cut -f1` ]; then
	echo "Api is up to date"
else
    echo "Pulling tests..."
    git pull
    SHOULDTEST = true
fi

if ["$SHOULDTEST" = true]; then
	echo "There were new commits! Testing..."
	cd ~/testing
	php cliTest.php
fi