#!/bin/sh

branch="development"
if [ "$#" -ne 1 ]; then
	echo "Assuming branch $branch";
else
	branch=$1;
fi

echo "Deleting custom files"
rm -f testApi/settings.php
rm -f testApi/secret.php

cd /home/test.infected.no/public_html/test

ssh-agent bash -c 'ssh-add /home/test.infected.no/.ssh/id_rsa; git pull origin master'

cd /home/test.infected.no/public_html/test/deploymentData

ssh-agent bash -c 'ssh-add /home/test.infected.no/.ssh/id_rsa; git pull origin master'

cd /home/test.infected.no/public_html/test/testApi

#git checkout -- .
echo "Pulling out $branch"
ssh-agent bash -c 'ssh-add /home/test.infected.no/.ssh/id_rsa; git pull origin $branch'
ssh-agent bash -c 'ssh-add /home/test.infected.no/.ssh/id_rsa; git fetch origin'
ssh-agent bash -c 'ssh-add /home/test.infected.no/.ssh/id_rsa; git checkout $branch'

cd /home/test.infected.no/public_html/test

cp settings_test.php testApi/settings.php

cp test_secret.php testApi/secret.php