#!/bin/sh

branch="development"
if [ "$#" -ne 1 ]; then
	echo "Assuming branch $branch";
else
	branch=$1;
fi

echo "Deleting custom files"
rm testApi/settings.php
rm testApi/secret.php

cd /home/test.infected.no/public_html/test

git pull origin master

cd /home/test.infected.no/public_html/test/deploymentData

git pull origin master

cd /home/test.infected.no/public_html/test/testApi

#git checkout -- .
echo "Pulling out $branch"
git pull origin $branch
git fetch origin
git checkout $branch

cd /home/test.infected.no/public_html/test

cp settings_test.php testApi/settings.php

cp test_secret.php testApi/secret.php