#!/bin/sh

cd /home/test.infected.no/public_html/test

git pull origin master

cd /home/test.infected.no/public_html/test/deploymentData

git pull origin master

cd /home/test.infected.no/public_html/test/testApi

git pull origin master

cd /home/test.infected.no/public_html/test

rm testApi/settings.php
cp settings_test.php testApi/settings.php

rm testApi/secret.php
cp test_secret.php testApi/secret.php